import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  containerHeader: {
    width: '100%',
    height: 60,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderBottomWidth: 0.2,
    borderBottomColor: 'black',
  },
  sourceProblemTitle: {
    color: '#000000',
    fontSize: 14,
    marginTop: 10,
    marginBottom: 5,
    fontWeight: '500',
  },
    clickImage: {
    width: 40,
    height: 40,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
  },
  inputSource: {
    width: '100%',
    height: 45,
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 10,
    paddingLeft: 10,
    backgroundColor: '#FFFFFF',
    color: 'black',
  },
  containerCheckbox: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 10,
    height: 35,
  },
  checkboxTop: {
    width: '80%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleCheckbox: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '500',
    paddingLeft: 15,
  },
  containerList: {
    width: '100%',
    height: 180,
  },
  blockCheckbox: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    height: 30,
    // marginBottom: 10,
  },
  containerContent: {width: '100%', height: '100%', paddingHorizontal: 10},
  titleHeader: {fontSize: 15, color: 'black'},
  clickContainer: {position: 'absolute', top: '55%', right: '2%', zIndex: 99},
  clickBlock: {
    width: 55,
    height: 55,
    borderRadius: 55,
    backgroundColor: '#7460BE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerModal: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  containerBlock: {
    width: '100%',
    height: 120,
    backgroundColor: 'white',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    paddingHorizontal: 10,
  },
  itemSheet: {
    width: '100%',
    height: 30,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  imageSheet: {width: 15, height: 15, marginRight: 10},
  titleSheet: {
    fontSize: 12,
    color: 'black',
  },
  modalBlock: {
    width: '100%',
    height: 120,
    // backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    paddingLeft: 15,
  },
  fullWidth: {width: '100%', height: '100%'},
  containerImage: {
    width: '100%',
    height: 100,
    marginTop: 15,
    paddingHorizontal: 10,
  },
  blockImage: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
  },
  imageLeft: {
    width: '30%',
    height: '100%',
    backgroundColor: 'yellow',
  },
  imageClick: {width: '100%', height: '100%', zIndex: 0},
  closeIcon: {
    position: 'absolute',
    top: -12,
    right: -9,
    zIndex: 99,
  },
  imageRightContainer: {
    width: '70%',
    height: '100%',
    marginLeft: 8,
    flexDirection: 'row',
  },
  imageRight_left: {
    width: '90%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputRight: {
    borderWidth: 1,
    borderColor: '#DCDCDC',
    height: 45,
    borderRadius: 9,
    width: '100%',
    color: 'black',
  },
  imagRight_right: {
    width: '15%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },

  closeContainer: {
    width: '100%',
    height: '30%',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingRight: 10,
  },
  imageContainer: {width: '100%', height: '40%', backgroundColor: 'green'},
  inputContainer: {
    width: '100%',
    height: '30%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingHorizontal: '15%',
    paddingBottom: '15%',
  },
  inputDetail: {
    width: '100%',
    height: 35,
    backgroundColor: 'white',
    borderRadius: 9,
    paddingTop: 0,
    paddingBottom: 0
  },
});

export default styles;
