import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  containerHeader: {
    width: '100%',
    height: 60,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderBottomWidth: 0.2,
    borderBottomColor: 'black',
  },
  fullWidth: {width: '100%', height: '100%'},
  blockWidth: {
    width: '100%',
    height: '100%',
    paddingHorizontal: 12,
  },
  sourceProblemTitle: {
    color: '#000000',
    fontSize: 14,
    marginTop: 10,
    marginBottom: 5,
    fontWeight: '500',
  },
  inputSource: {
    width: '100%',
    height: 45,
    borderWidth: 1,
    borderColor: '#E1E1E1',
    borderRadius: 10,
    paddingLeft: 10,
    backgroundColor: '#FFFFFF',
  },
  clickContainer: {
    width: '100%',
    height: 50,
    backgroundColor: '#D9D9D9',
    paddingHorizontal: 10,
    marginTop: 20,
    borderRadius: 12,
    marginBottom: 10,
  },
  blockClick: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  clickImage: {
    width: 40,
    height: 40,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    // backgroundColor: 'green',
  },
  blockCamera: {
    width: '100%',
    height: 80,
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  camearaItem: {
    width: '100%',
    height: '50%',
    borderBottomWidth: 0.6,
    borderBottomColor: '#000000',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 11,
  },
  black: {
    color: '#000000',
  },
  containerImage: {
    width: '100%',
    height: 80,
    marginTop: 15,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  blockImage: {
    width: '100%',
    height: '100%',
    flexDirection: 'row',
  },
  imageLeft: {
    width: '30%',
    height: '100%',
    backgroundColor: 'yellow',
  },
  imageClick: {width: '100%', height: '100%', zIndex: 0},
  closeIcon: {
    position: 'absolute',
    top: -12,
    right: -9,
    zIndex: 99,
  },
  imageRightContainer: {
    width: '70%',
    height: '100%',
    marginLeft: 8,
    flexDirection: 'row',
  },
  imageRight_left: {
    width: '85%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputRight: {
    borderWidth: 1,
    borderColor: '#DCDCDC',
    height: 45,
    borderRadius: 9,
    width: '100%',
    color: 'black',
  },
  imagRight_right: {
    width: '15%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainerInput: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  textModalInput: {alignSelf: 'flex-start', color: '#C8C8C8', fontSize: 15},
  inputBlock: {
    width: '100%',
    height: 100,
    borderRadius: 9,
    backgroundColor: 'white',
  },
  input: {width: '100%', height: '80%'},
  clickSave: {
    width: 60,
    height: '20%',
    borderRadius: 5,
    backgroundColor: '#41AE6C',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginRight: 20,
  },
  white: {
    color: 'white',
  },
  closeIconClick: {
    position: 'absolute',
    top: 10,
    right: 20,
    zIndex: 99,
  },
  modalInputTop: {
    width: '100%',
    height: '65%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  imageModal: {width: '100%', height: 200, backgroundColor: 'blue'},
  modalInputBottom: {
    width: '100%',
    height: '35%',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  containerCheckbox: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 10,
    height: 35,
  },
  checkboxTop: {
    width: '80%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxBottom: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  titleCheckbox: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '500',
    paddingLeft: 15,
  },
  blockSearch: {
    width: 23,
    height: 23,
    backgroundColor: '#D9D9D9',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  blockCheckbox: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    height: 30,
    marginBottom: 10,
  },
  containerList: {
    width: '100%',
    height: 180,
  },
  inputSearchContainer: {
    width: '100%',
    flexDirection: 'row',
    height: 35,
    marginTop: 15,
  },
  iconInput: {
    width: '8%',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  inputRightBlock: {
    width: '100%',
    borderRadius: 9,
    backgroundColor: '#D9D9D9',
    paddingTop: 0,
    paddingBottom: 0,
    fontSize: 12,
  },
  inputRightContainer: {
    width: '80%',
  },
  error: {color: 'red', marginVertical: 10},
});

export default styles;
